default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rbt_1_development

test:
  <<: *default
  database: rbt_1_test

production:
  <<: *default
  database: rbt_1_production
  username: rbt_1
  password: <%= ENV['RBT_1_DATABASE_PASSWORD'] %>
